### ISSUE TITLE
Cannot import data to mapping module

### ISSUE THREAD

**Issue by hydrosIII** [Daniel-KM/Omeka-plugin-CsvImportPlus#12]
If you do imports using these plugins, everythng works fine but there is not at option to import geolocation coordinates to mapping module. The omeka csv importer has this option.

**Comment by Daniel-KM** [comment]
See an example here: https://github.com/Daniel-KM/Omeka-plugin-CsvImportPlus/blob/master/csv_files/test_extra_data.csv
